import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import { ModeToggle } from "@/components/mode-toggle";
import Navbar from "@/components/navbar";
import ClickEffect from "@/components/ClickEffect";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body
        className={`antialiased min-h-screen ${inter.variable} font-sans text-slate-900 dark:text-slate-50`}
      >
        <div className="fixed inset-0 -z-20 bg-grid" />
        <ClickEffect />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="relative flex flex-col items-center px-4 min-h-screen">
            <div className="w-full max-w-6xl bg-white dark:bg-slate-900/70 rounded-2xl shadow-xl ring-1 ring-black/5 backdrop-blur-lg p-4 sm:p-6 md:p-8 z-10 min-h-screen flex flex-col">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4 sm:mb-6 gap-2 relative w-full">
                <div className="text-2xl sm:text-xl font-bold bg-gradient-to-r from-purple-500 to-pink-500 text-transparent bg-clip-text text-center sm:text-left">
                  Blogify
                </div>
                <div className="absolute right-0 top-0 sm:hidden">
                  <ModeToggle />
                </div>
                <Navbar />
                <div className="hidden sm:flex justify-end">
                  <ModeToggle />
                </div>
              </div>

              <main className="flex-1">{children}</main>
              <footer className="text-center text-sm text-muted-foreground">
                © {new Date().getFullYear()} bionicbear. All rights reserved. |{" "}
                <a
                  href="https://github.com/suhao0628/bionicbear"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-purple-500 hover:underline"
                >
                  <i className="devicon-github-original" aria-hidden="true"></i>
                  <span>View on GitHub</span>
                </a>
              </footer>
            </div>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
